### ISSUE TITLE
DEP 5: Needs more discussion of the effects of changing semantics

### ISSUE THREAD

**Issue by marfire** [django/deps#21]
The new approach to middleware in DEP 5 looks great, making it simpler and more elegant.

One thing that wasn't clear to me was exactly *why* the old approach had the semantics it did. For example, was there a good reason for making a short-circuited response pass through all the layers (not just the ones above)? Are there any known middleware classes in the Django ecosystem that depend on that functionality? If so, how will this change impact them?

The DEP points out that the new design "allows more powerful idioms that aren't currently possible", but doesn't say whether it makes impossible some idioms that are currently possible. Perhaps it's the case that these foreclosed possibilities (for example, as above, modifying all responses even if the request was short-circuited by a higher layer) aren't useful and don't exist, but either way it would be great to see that explicitly acknowledged in the DEP.

**Comment by jacobian** [comment]
The initial design was mine, but sadly that was so long ago (10 years) that I've forgotten the motivation.

**Comment by carljm** [comment]
Yeah, I wasn't around ten years ago and obviously don't know about the original motivations either. My best _guess_ is that it just fell out naturally from the previous implementation and may not have been given a lot of specific thought: when you have separate `process_request` and `process_response` methods (and the implementation splits them up into separate lists early on, not keeping track of the links between them at all), it's a lot simpler to just run through all of them at the appropriate spot in the request handler than to keep track of which ones were short-circuited and which weren't. One small bit of evidence is that the [original middleware documentation](https://github.com/django/django/commit/072a89ace2d228bcf945ca1a3966be984d0b2531) contains only brief (and somewhat misleading) references to the short-circuiting behavior.

As to whether the previous behavior is useful in cases that will be harder with the new behavior, that's a hard question to answer definitively, because it can't really even be answered by looking at individual middleware, it's a matter of how multiple middleware interact with each other (and often involves judgment calls as to which behavior is desired). So it's something that has to be evaluated more case by case at the project level than at the middleware level. I have spent some time looking through GitHub code searches for `MIDDLEWARE_CLASSES` and haven't yet found any cases that wouldn't be workable under the new idiom. I think in the vast majority of cases, developers won't have previously thought about it at all, and probably wrongly assumed onion-style short-circuiting anyway.

The one use case I'm aware of that on its face is a bit harder with the new system is something like "I want to handle _all_ 404 responses, no matter where they came from." But this was never fully possible to begin with unless you were the first middleware listed, because otherwise an earlier-listed (thus later in response cycle) middleware could transform some other response to a 404 in its `process_response` and you'd never see it. So middlewares that care about seeing all responses are _already_ telling users "put me first in the list," and that advice will remain just as correct (and necessary) under the new system.

Thanks for raising the question - dunno if the above answers it at all. I'll try to put some wording together for the DEP that acknowledges this.

**Comment by carljm** [comment]
Also, I think the fact that Pyramid has already been using a system very much like the DEP 5 one for years and hasn't had trouble with it is a pretty strong indicator that there aren't important use cases that are just impossible with this system.

**Comment by dstufft** [comment]
One thing that Pyramid's tweens don't allow that Django's previous middleware does is doing something conditional based on the specific view that is being invoked. Pyramid added "view derivers" to combat that problem but a quick skim of DEP 5 suggests it has a similar limitation. That's not a "OMG Don't Merge This!" but it's good to be explicit about it I think.

**Comment by carljm** [comment]
DEP 5 preserves the `process_view` hook from the old middleware system, so I don't think we're losing anything in that regard.

**Comment by dstufft** [comment]
Ooops, I missed that. CARRY ON.

**Comment by carljm** [comment]
@marfire I added some text in 4cec3c3d489823bd68d78877fb9db86223227618 -- let me know if that doesn't adequately address your question.

**Comment by marfire** [comment]
Looks good, but I also think it would be helpful to explicitly include a version of what you said above: "I have spent some time looking through GitHub code searches for MIDDLEWARE_CLASSES and haven't yet found any cases that wouldn't be workable under the new idiom."

That is, knowing that the DEP author looked for and failed to find existing code that would be incompatible would definitely be reassuring (to this reader, anyway).

**Comment by carljm** [comment]
eb0c2ed6536d5bbc673a28c3c6653179a8191d5e look OK?

**Comment by marfire** [comment]
Looks good!
